### ISSUE TITLE
Смоггер не стартует

### ISSUE THREAD

**Issue by romanbubnovmoretv** [m3-moretv/smogger#1]
При попытке поднять сервер падает с ошибкой:
```bash
$ npx @m3-moretv/smogger -p 4200 -s ./spec.yaml
/<secret-path>/node_modules/ballboy/lib/index.js:57
      resolve(data.toString());
                   ^

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext._fs.default.readFile [as callback] (/<secret-path>/node_modules/ballboy/lib/index.js:57:20)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
error Command failed with exit code 1.
```

**Comment by MrFranke** [comment]
@romanbubnovmoretv скорее всего файла `./spec.yaml` по этому пути нет.
